# Generated by Django 5.2.9 on 2026-01-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kolekcja', '0002_film_plakat'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='ocena',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
